syntax on
set splitbelow


call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'ycm-core/YouCompleteMe'
call plug#end()

let mapleader = ' '
set encoding=UTF-8
set signcolumn=yes

"let g:EclimCompletionMethod = 'omnifunc'
"imap <Tab> <C-P>

let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1
" let g:SuperTabClosePreviewOnPopupClose = 1
let g:ycm_global_ycm_extra_conf = '~/.vim/plugged/YouCompleteMe/.ycm_extra_conf.py'


imap jj <ESC>

nnoremap <Leader>e :<ESC> :bw<CR>

autocmd Filetype python nnoremap <buffer> <Leader>r :w<CR>:ter python3 "%"<CR>

colorscheme gruvbox
set background=dark
let g:gruvbox_constrast_dark='hard'
