#!/bin/sh

clock() {
	DATE=$(date "+%m.%d.%y")
	TIME=$(date "+%I.%M")
	echo -e -n "\uf073 ${DATE} \uf017 ${TIME}"
}

battery() {
    	BATC=$(cat /sys/class/power_supply/battery/capacity)
    	BATS=/sys/class/power_supply/battery/status

    	echo -e -n "\uf06e ${BATC}"

}


while true; do
	echo -e "$(clock) $(battery)"
	sleep 1
done
